// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8FchSsiiZWHae7vc9L6pbp
// Component: 30z5b-PBzeQR

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";
import "../plasmic__default_style.css"; // plasmic-import: global/defaultcss

import "./plasmic.css"; // plasmic-import: 8FchSsiiZWHae7vc9L6pbp/projectcss
import "./PlasmicPackedLogo.css"; // plasmic-import: 30z5b-PBzeQR/css

import image2F4Hzd2A8XEz6 from "./images/image2.png"; // plasmic-import: f4HZD2a8xEZ6/picture

createPlasmicElementProxy;

export type PlasmicPackedLogo__VariantMembers = {};
export type PlasmicPackedLogo__VariantsArgs = {};
type VariantPropType = keyof PlasmicPackedLogo__VariantsArgs;
export const PlasmicPackedLogo__VariantProps = new Array<VariantPropType>();

export type PlasmicPackedLogo__ArgsType = {};
type ArgPropType = keyof PlasmicPackedLogo__ArgsType;
export const PlasmicPackedLogo__ArgProps = new Array<ArgPropType>();

export type PlasmicPackedLogo__OverridesType = {
  logoText?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  text?: Flex__<"div">;
};

export interface DefaultPackedLogoProps {
  className?: string;
}

const $$ = {};

function PlasmicPackedLogo__RenderFunc(props: {
  variants: PlasmicPackedLogo__VariantsArgs;
  args: PlasmicPackedLogo__ArgsType;
  overrides: PlasmicPackedLogo__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <div
      data-plasmic-name={"logoText"}
      data-plasmic-override={overrides.logoText}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "plasmic_default__all",
        "plasmic_default__div",
        "root_reset_8FchSsiiZWHae7vc9L6pbp",
        "plasmic_default_styles",
        "plasmic_mixins",
        "plasmic_tokens",
        "PackedLogo__logoText__zBt7Q"
      )}
    >
      <PlasmicImg__
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames("PackedLogo__img__uCuOf")}
        displayHeight={"auto"}
        displayMaxHeight={"none"}
        displayMaxWidth={"100%"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"25%"}
        loading={"lazy"}
        src={{
          src: image2F4Hzd2A8XEz6,
          fullWidth: 500,
          fullHeight: 500,
          aspectRatio: undefined
        }}
      />

      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(
          "plasmic_default__all",
          "plasmic_default__div",
          "__wab_text",
          "PackedLogo__text__scrRg"
        )}
      >
        {"Placeholder Inc."}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  logoText: ["logoText", "img", "text"],
  img: ["img"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  logoText: "div";
  img: typeof PlasmicImg__;
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPackedLogo__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPackedLogo__VariantsArgs;
    args?: PlasmicPackedLogo__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPackedLogo__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicPackedLogo__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPackedLogo__ArgProps,
          internalVariantPropNames: PlasmicPackedLogo__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPackedLogo__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "logoText") {
    func.displayName = "PlasmicPackedLogo";
  } else {
    func.displayName = `PlasmicPackedLogo.${nodeName}`;
  }
  return func;
}

export const PlasmicPackedLogo = Object.assign(
  // Top-level PlasmicPackedLogo renders the root element
  makeNodeComponent("logoText"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicPackedLogo
    internalVariantProps: PlasmicPackedLogo__VariantProps,
    internalArgProps: PlasmicPackedLogo__ArgProps
  }
);

export default PlasmicPackedLogo;
/* prettier-ignore-end */
